var character = 'mario';
var age;
var isLoggedIn;
age = 30;
isLoggedIn = true;
var ninjas = [];
ninjas.push('ryu');
ninjas.push('chun-li');
console.log(ninjas);
var mixed = [];
mixed.push('hello');
mixed.push(false);
mixed.push(20);
var uid;
var ninjaOne;
ninjaOne = { name: 'yoshi', age: 30 };
var ninjaTwo;
ninjaTwo = { name: 'ken', age: 20, beltColour: 'black' };
